env:
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "airbnb-base"
  - "plugin:jest/recommended"
  - "prettier"
plugins:
  - jest
  - prettier
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  comma-dangle: off
  implicit-arrow-linebreak: off
  linebreak-style: off
  prettier/prettier: ["warn", { endOfLine: "crlf" }]
