env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - 'airbnb-base'
  - 'plugin:jest/recommended'

plugins:
  - jest
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  comma-dangle: off
  implicit-arrow-linebreak: off
  linebreak-style: off